services:
  - type: web
    name: ai-food-calorie-nutrition
    env: python
    rootDir: AI-Food-Calorie-Nutrition
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
